### ISSUE TITLE
When clicking instructions crash  , please someone solve it

### ISSUE THREAD

**Issue by ELJOKER900** [CoffeeCatRailway/BubbleBurst#2]
there are the log

$200(HttpURLConnection.java:90)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at com.mrcrayfish.device.api.app.component.Image$DynamicLoader.lambda$setup$0(Image.java:409)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at com.mrcrayfish.device.api.app.component.Image$DynamicLoader$$Lambda$1560/446855030.run(Unknown Source)
[16:57:32] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.lang.Thread.run(Thread.java:745)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: java.net.UnknownHostException: mastefchief.com
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.net.Socket.connect(Socket.java:589)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.net.Socket.connect(Socket.java:538)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
[16:57:85] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:988)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:986)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:985)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at com.mrcrayfish.device.api.app.component.Image$DynamicLoader.lambda$setup$0(Image.java:409)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at com.mrcrayfish.device.api.app.component.Image$DynamicLoader$$Lambda$1560/446855030.run(Unknown Source)
[16:57:86] [Image Loader/INFO]: [com.mrcrayfish.device.api.app.component.Image$DynamicLoader:lambda$setup$0:417]: 	at java.lang.Thread.run(Thread.java:745)
[16:57:76] [Client thread/WARN]: Failed to load texture: cdm:textures/app/banner/pixel_painter.png
java.io.FileNotFoundException: cdm:textures/app/banner/pixel_painter.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:40)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at com.mrcrayfish.device.api.app.component.Image$StandardLoader.load(Image.java:375)
	at com.mrcrayfish.device.api.app.component.Image.render(Image.java:185)
	at com.mrcrayfish.device.api.app.Layout.render(Layout.java:189)
	at com.mrcrayfish.device.api.app.Application.render(Application.java:134)
	at com.mrcrayfish.device.core.Window.render(Window.java:117)
	at com.mrcrayfish.device.core.Laptop.func_73863_a(Laptop.java:255)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[16:57:81] [Client thread/INFO]: Sprite [bubble_burst:textures/app/sprites/fire_ball/default/anim0.png] has been loaded!
[16:57:82] [Client thread/INFO]: Sprite [bubble_burst:textures/app/sprites/fire_ball/default/anim1.png] has been loaded!
[16:59:85] [Client thread/INFO]: Sprite [bubble_burst:textures/app/sprites/fire_ball/default/anim0.png] has been loaded!
[16:59:85] [Client thread/INFO]: Sprite [bubble_burst:textures/app/sprites/fire_ball/default/anim1.png] has been loaded!
[16:59:95] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 30291ms behind, skipping 605 tick(s)
[16:59:05] [Client thread/INFO]: Mapping halted in C:\Users\alber\AppData\Roaming\.minecraft\versions\HYPER\journeymap\data\sp\no entrar\DIM0
[16:59:11] [Client thread/WARN]: Couldn't copy color palette html: java.lang.NullPointerException
[16:59:11] [Client thread/ERROR]: Can't write colorpalette.html: java.lang.NullPointerException
[16:59:11] [Client thread/WARN]: Existing color palette's mods no longer match current loadout.
[16:59:11] [Client thread/INFO]: WAS: AutoRegLib:1.3-32, CodeChicken Lib:3.2.3.358, Decocraft:2.6.3.7, FPS Reducer:mc1.12.2-1.20, Forge Microblocks:2.6.2.83, Forge Mod Loader:8.0.99.99, Forge Multipart CBE:2.6.2.83, Grappling hook mod:1.12.2-v13, HBM's Nuclear Tech - Extended Edition:NTM-Extended-1.12.2-1.9.8, Immersive Engineering:0.12-98, IndustrialCraft 2:2.8.222-ex112, JourneyMap:1.12.2-5.7.1, Just Enough Items:4.16.1.1001, Mekanism: Generators:1.12.2-9.8.3.390, Mekanism:1.12.2-9.8.3.390, Memory Bar:1.0.7, Minecraft Chromium Embedded Framework:0.9, Minecraft Coder Pack:9.42, Minecraft Forge:14.23.5.2859, Minecraft Multipart Plugin:2.6.2.83, Minecraft:1.12.2, More Sound Config Core:1.0.0, More Sound Config:1.0.4, MrCrayfish's Device Mod:0.4.1, MrCrayfish's Furniture Mod:6.3.0, MrCrayfish's Vehicle Mod:0.44.1, MrTJPCore:2.1.4.43, Obfuscate:0.4.2, OpenComputers (Core):1.8.3, OpenComputers:1.8.3, ProjectRed Core:4.9.4.120, ProjectRed Expansion:4.9.4.120, ProjectRed Illumination:4.9.4.120, ProjectRed Integration:4.9.4.120, ProjectRed Relocation:4.9.4.120, ProjectRed Transmission:4.9.4.120, ProjectRed Transportation:4.9.4.120, Quark:r1.6-179, Realistic Terrain Generation:6.1.0.0-snapshot.1, Rex's Additional Structures:2.5.0, SecurityCraft:v1.9.7, Techguns Core:1.12.2-1.0, Techguns:2.0.2.0, Waila:1.8.26, WebDisplays:1.0, WorldEdit:6.1.10, YUNG's Better Caves:1.12.2, ptrmodellib:1.0.5
NOW: AutoRegLib:1.3-32, Bubble Burst:3.1, CodeChicken Lib:3.2.3.358, Decocraft:2.6.3.7, FPS Reducer:mc1.12.2-1.20, Forge Microblocks:2.6.2.83, Forge Mod Loader:8.0.99.99, Forge Multipart CBE:2.6.2.83, GitWeb Builder:1.1, HBM's Nuclear Tech - Extended Edition:NTM-Extended-1.12.2-1.9.8, Immersive Engineering:0.12-98, IndustrialCraft 2:2.8.222-ex112, JourneyMap:1.12.2-5.7.1, Just Enough Items:4.16.1.1001, Mekanism: Generators:1.12.2-9.8.3.390, Mekanism:1.12.2-9.8.3.390, Memory Bar:1.0.7, Memory Cleaner:1.4, Minecraft Coder Pack:9.42, Minecraft Forge:14.23.5.2859, Minecraft Multipart Plugin:2.6.2.83, Minecraft:1.12.2, More Sound Config Core:1.0.0, More Sound Config:1.0.4, MrCrayfish's Device Mod:0.4.1, MrTJPCore:2.1.4.43, OpenComputers (Core):1.8.3, OpenComputers:1.8.3, ProjectRed Core:4.9.4.120, ProjectRed Expansion:4.9.4.120, ProjectRed Integration:4.9.4.120, ProjectRed Relocation:4.9.4.120, ProjectRed Transmission:4.9.4.120, ProjectRed Transportation:4.9.4.120, Quark:r1.6-179, Realistic Terrain Generation:6.1.0.0-snapshot.1, Rex's Additional Structures:2.5.0, SecurityCraft:v1.9.7, Techguns Core:1.12.2-1.0, Techguns:2.0.2.0, Waila:1.8.26, WorldEdit:6.1.10, ptrmodellib:1.0.5
[16:59:33] [Server thread/INFO]: Stopping server
[16:59:33] [Server thread/INFO]: Saving players
[16:59:37] [Server thread/INFO]: Saving worlds
[16:59:37] [Server thread/INFO]: Saving chunks for level 'no entrar'/overworld
[16:59:59] [Server thread/INFO]: Unloading dimension 0
[16:59:47] [Server thread/INFO]: Applying holder lookups
[16:59:47] [Server thread/INFO]: Holder lookups applied
[17:00:98] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1772)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at coffeecatteam.bubbleburst.app.layouts.instructions.LayoutInstructions.init(LayoutInstructions.java:55)
	at com.mrcrayfish.device.api.app.Layout.handleLoad(Layout.java:131)
	at com.mrcrayfish.device.api.app.Application.setCurrentLayout(Application.java:77)
	at coffeecatteam.bubbleburst.app.ApplicationGame.lambda$init$1(ApplicationGame.java:91)
	at coffeecatteam.bubbleburst.app.ApplicationGame$$Lambda$1564/481374660.onClick(Unknown Source)
	at com.mrcrayfish.device.api.app.component.Button.handleMouseClick(Button.java:278)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:238)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:162)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:204)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:323)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:444)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	... 9 more

[17:00:13] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.7.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 10/7/23 5:00 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at coffeecatteam.bubbleburst.app.layouts.instructions.LayoutInstructions.init(LayoutInstructions.java:55)
	at com.mrcrayfish.device.api.app.Layout.handleLoad(Layout.java:131)
	at com.mrcrayfish.device.api.app.Application.setCurrentLayout(Application.java:77)
	at coffeecatteam.bubbleburst.app.ApplicationGame.lambda$init$1(ApplicationGame.java:91)
	at coffeecatteam.bubbleburst.app.ApplicationGame$$Lambda$1564/481374660.onClick(Unknown Source)
	at com.mrcrayfish.device.api.app.component.Button.handleMouseClick(Button.java:278)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:238)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:162)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:204)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:323)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:444)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at coffeecatteam.bubbleburst.app.layouts.instructions.LayoutInstructions.init(LayoutInstructions.java:55)
	at com.mrcrayfish.device.api.app.Layout.handleLoad(Layout.java:131)
	at com.mrcrayfish.device.api.app.Application.setCurrentLayout(Application.java:77)
	at coffeecatteam.bubbleburst.app.ApplicationGame.lambda$init$1(ApplicationGame.java:91)
	at coffeecatteam.bubbleburst.app.ApplicationGame$$Lambda$1564/481374660.onClick(Unknown Source)
	at com.mrcrayfish.device.api.app.component.Button.handleMouseClick(Button.java:278)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:238)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:162)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:204)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:323)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:444)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.mrcrayfish.device.core.Laptop

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['albertoz909'/27, l='MpServer', x=518.50, y=4.15, z=-436.50]]
	Chunk stats: MultiplayerChunkCache: 729, 729
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (567,6,-948), Chunk: (at 7,0,12 in 35,-60; contains blocks 560,0,-960 to 575,255,-945), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 168662 game time, 440374 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 15 total; [EntityXPOrb['Orbe de experiencia'/33, l='MpServer', x=663.75, y=4.00, z=-525.35], EntityPlayerSP['albertoz909'/27, l='MpServer', x=518.50, y=4.15, z=-436.50], EntityXPOrb['Orbe de experiencia'/221, l='MpServer', x=661.40, y=4.00, z=-528.38], AlienBug['Alien Bug'/1527, l='MpServer', x=518.55, y=4.00, z=-505.26], EntityItem['item.tile.router'/1533, l='MpServer', x=522.29, y=4.00, z=-438.01], EntityItem['item.tile.office_chair'/1536, l='MpServer', x=521.88, y=4.00, z=-438.09], EntityItem['item.tile.laptop'/1538, l='MpServer', x=522.00, y=4.00, z=-438.00], EntitySeat['entity.Seat.name'/1542, l='MpServer', x=518.50, y=4.50, z=-436.50], AlienBug['Alien Bug'/1574, l='MpServer', x=520.25, y=4.00, z=-505.26], EntitySlime['Slime'/1584, l='MpServer', x=597.59, y=4.14, z=-402.77], EntitySlime['Slime'/1586, l='MpServer', x=552.53, y=4.95, z=-496.90], AlienBug['Alien Bug'/1587, l='MpServer', x=515.34, y=4.00, z=-510.15], EntitySlime['Slime'/1591, l='MpServer', x=521.99, y=4.67, z=-419.88], EntitySlime['Slime'/1596, l='MpServer', x=590.97, y=4.00, z=-495.93], AlienBug['Alien Bug'/1597, l='MpServer', x=513.55, y=4.00, z=-509.76]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

my minecraft version is 1.12.2

**Comment by ELJOKER900** [comment]
well nobody answers...

**Comment by ELJOKER900** [comment]
anyways i think this is an HTTP error...
